name: Hotfix
on:
  push:
    branches: [ 'release/**' ]

permissions: {}

jobs:
  default:
    uses: cloudposse/example-github-action-release-workflow/.github/workflows/reusable-hotfix.yml@release/0.38.0
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      registry: 252494810635.dkr.ecr.us-east-2.amazonaws.com
      default_branch: main
    secrets:
      github-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"