name: Release
on:
  release:
    types: [published]

permissions: {}

jobs:
  default:
    uses: cloudposse/example-github-action-release-workflow/.github/workflows/reusable-release.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      registry: 252494810635.dkr.ecr.us-east-2.amazonaws.com
      version: ${{ github.event.release.tag_name }}
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"