name: Reusable - Build
on:
  workflow_call:
    inputs:
      enabled:
        required: true
        default: false
        type: boolean
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
    outputs:
      image:
        description: "Docker image name"
        value: ${{ jobs.build.outputs.image }}
      tag:
        description: "Docker image tag"
        value: ${{ jobs.build.outputs.tag }}

##
##  Example how to use private shared actions
##
#    secrets:
#      github-pat:
#        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: inputs.enabled
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ##
      ##  Example how to use private shared actions
      ##
      #      - name: Checkout private actions
      #        uses: actions/checkout@v2
      #        with:
      #          repository: ${{ inputs.organization }}/github
      #          token: ${{ secrets.github-pat }}
      #          path: github

      - name: Build
        id: build
        uses: ./github-shared-actions/actions/build
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}
          registry: ${{ inputs.registry }}

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}
